# the action is a scheduled task to run the puppeteer program
# in the actions directory. it runs every night at 11:00pm CST

name: "Scrape Ebay Listings"
on:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - main
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm i
      - name: Compile TypeScript to JavaScript
        run: npm run build
      - name: Run scraper
        run: node dist/actions/scrapeEbayCardData.js
