# the action is a scheduled task to run the puppeteer program
# in the actions directory. it runs every night at 11:00pm CST
# it uses pnpm to install the dependencies and then runs the
# ts-node command to run the program

name: "Scrape Ebay Listings"
on:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - main
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - name: Go to actions directory
        run: cd actions
      - name: Install dependencies
        run: pnpm install
      - name: Run program
        run: pnpm run start-ebay
