name: Scrape eBay Listings

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change this to your preferred Node.js version

      - name: Run Puppeteer script
        run: |
          cd actions
          npm install
          npm run build
          node ./dist/scrapeEbayListings.js
