name: Scrape eBay Listings

on:
  push:
    branches:
      - main # Change this to your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can change this to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript
        run: npm run build # You can change this if your build script is different

      - name: Run Puppeteer script
        run: node actions/scrapeEbayListings.js # Make sure to adjust the path to your TypeScript file

